host: madr.cluster.local

images:
  api: madr/api:latest
  pg: postgres:16.4

volumes:
  storageClassName: standard

api:
  replicaCount: 1

pg:
  user: postgres
  password: postgres
  database: madr
  storage_size: 1Gi
