apiVersion: v1
kind: Secret
metadata:
  name: {{ include "madr.fullname" . }}-api
  labels:
    {{- include "madr.labels" . | nindent 4 }}
    app.kubernetes.io/tier: api
type: Opaque
stringData:
  SECRET_KEY: {{.Values.api.secretKey }}
  DATABASE_URL: postgresql+psycopg://{{ .Values.pg.user }}:{{ .Values.pg.password }}@{{ include "madr.fullname" . }}-pg:5432/{{ .Values.pg.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "madr.fullname" . }}-pg
  labels:
    {{- include "madr.labels" . | nindent 4 }}
    app.kubernetes.io/tier: db
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.pg.user }}
  POSTGRES_PASSWORD: {{ .Values.pg.password }}
  POSTGRES_DB: {{ .Values.pg.database }}
