apiVersion: v1
kind: Service
metadata:
  name: {{ include "madr.fullname" . }}-api
  labels:
    {{- include "madr.labels" . | nindent 4 }}
    app.kubernetes.io/tier: api
spec:
  selector:
    {{- include "madr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/tier: api
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
