services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    command: sleep infinity
    environment:
      PGHOST: 127.0.0.1
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: madr
    volumes:
      - ../..:/workspaces:cached
  pg:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madr
    volumes:
      - pg-data:/var/lib/postgresql/data
    network_mode: service:dev
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 4
  pgadmin:
    image: dpage/pgadmin4:8.10
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: user@test.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
      - pgadmin-data:/var/lib/pgadmin
    network_mode: service:dev
volumes:
  pg-data:
  pgadmin-data:
