name: Check Commit

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Check Lints
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry==1.8.3

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --sync

      - name: Run lints
        run: make lint

  test:
    name: Check Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry==1.8.3

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --sync

      - name: Run tests
        run: make test
